### ISSUE TITLE
enhancements

### ISSUE THREAD

**Issue by waynebrantley** [andrewdavey/postal#1]
I like what you have created, looks cool.  Few issues.

1)  It is tied to the 'email' view folder.  I may want to provide the 'view' from a database or something dynamic - so, the email service needs to be uncoupled from where it gets the view.

2)  The header in the email are a neat concept, but has problems.   I would rather this 'email' actually just return the formatted email object (with list of alternate views, etc) and then using that I can send the email myself.  What if I want the email to go out to 100 people - same email - no need to run this code 100 times - just add the people as a 'to' in the regular email object.  What about email priority, bcc, cc, etc?   While you can have something that just sends the email (nice feature), I think this should have the ability to be 'uncoupled' from that, so the email can be sent 'manually', but still rendered by you, etc.

Anyway, those are just my thoughts - nice work!

**Comment by andrewdavey** [comment]
Thanks for the comments and suggestions.

1) You could add your own implementation of IViewEngine to the MVC ViewEngines collection. That could then pull views from anywhere you like.

2) You can get the generated MailMessage. Use an EmailService object and call CreateMailMessage(email). That will do everything, except sending the email. You can then do what ever you want with it. (And send using SmtpClient instead).

Bcc, CC and Reply-To all work. I'm missing Priority at the moment.

**Comment by waynebrantley** [comment]
1)  I guess what I was suggesting was more general...you request the view, try to locate it, etc - why not just let the developer pass in the string to use as a template?  
2)  Ok, nice - did not see that anywhere in the examples, etc.

3)  Bcc, cc, and replyto.....how do you specify multiple email addresses?

Thanks!

**Comment by andrewdavey** [comment]
1) Passing in a template string means Postal then has to worry about what template engine that string uses. I could in theory allowing passing in an IView object to render, but I think sticking with using the ViewEngine to find the view is simpler for me.
The other option is to implement your own IEmailViewRenderer and pass that to the EmailService. That lets you by-pass the ViewEngine stuff altogether then.

2) Good point - I'll have to update the wiki

3) You can specify the same header more than once. For example, Postal calls "mailMessage.Bcc.Add(emailAddress)" for each Bcc header.
(Again, I should update the wiki for this.)

**Comment by andrewdavey** [comment]
3) Or comma separate the email addresses in a single header.
