### ISSUE TITLE
Multiple TO recipients?

### ISSUE THREAD

**Issue by migig** [andrewdavey/postal#106]
Docs say I can have multiple CC and BCC recipients (as a csv or on separate lines).

But what if I want to have multiple TO recipients, just like in a normal email?

**Comment by andrewdavey** [comment]
Try adding multiple `To:` headers in your email view.

**Comment by migig** [comment]
Cool, works for both a csv and on separate lines.

Probably a good idea to update docs to say that it works this way for all three recipient fields: TO, CC, and BCC. (Not just CC and BCC)
