### ISSUE TITLE
Postal and 51Degrees.mobi Conflict

### ISSUE THREAD

**Issue by jpogran** [andrewdavey/postal#12]
First off, stellar product. Been using this since your session in mvcConf 2 and love the ease of use and feature set.

I recently started a project where I use Postal to send emails for certain parts of the site. Postal worked fine before I add 51Degrees.mobi to the mix. I use 51Degrees.mobi to detect if the browser is a mobile browser, and set the Layout according in a ASP.NET MVC 3 project, like so:

```
    Layout = Request.Browser.IsMobileDevice
             ? "~/Views/Shared/_LayoutMobile.cshtml"
             : "~/Views/Shared/_Layout.cshtml";
```

51Degrees.mobi (as stated here: http://51degrees.codeplex.com) uses an HttpModules to intercept the HttpRequests. Took me a little while to work out that Postal is presenting `Postal.EmailHttpRequest` as the HttpRequest, which does not implement the `Browser` property, which then throws an Exception that the method is not implemented.

Since I can't reflect on the type since `Postal.EmailHttpRequest` is internal or protected, I can't detect the different HttpRequest, or at least I don't know how. The immediate workaround I see is putting a `try{}catch{}` block around, but that doesn't sit write long term.

What do you recommend I do? This isn't Postal's fault, but I confess I don't know where to go to fix this.

**Comment by andrewdavey** [comment]
Thanks for reporting this issue. We can probably provide a non-throwing implementation of the Browser property. Since an email is being generated does it matter if the Browser property does not reflect the actual current browser?

**Comment by jpogran** [comment]
To me, I do not think it matters. Working around this point, the email generates successfully, so I agree a pseudo Browser property would work. Maybe just returns 'Postal' :)?

**Comment by andrewdavey** [comment]
I'm interested to know more about how 51degrees is intercepting the Postal view rendering. Is it getting into the view engine system? Are you able to post an expanded code snippet to help me understand?

**Comment by andrewdavey** [comment]
I've created a branch that adds a basic Browser property to EmailHttpRequest: https://github.com/andrewdavey/postal/tree/browser-property

Can you try it out for me, with 51degrees, and report back if it works or not? Thanks.

**Comment by jpogran** [comment]
I created a sample project with Postal and 51degrees up on github, https://github.com/jpogran/51degreesPostal , it has the essence of what I'm trying to do.

I'll clone the branch and test it out today and let you know. Thanks much!

**Comment by andrewdavey** [comment]
Excellent - thanks. I think I see what's happening now. The _viewstart.cshtml file at the top level of ~/Views runs first when a view is rendered. So I guess this is were the exception is being thrown.

The branch I created for you has a very naive Browser property, it returns a new HttpBrowserCapabilities object, which I assume pick ups information from HttpContext.Current. I will probably need to implement my own subclass instead and return some sensible defaults there.

**Comment by jpogran** [comment]
Think you might have to do that. Added Postal from the branch, and we get further and get a Browser object, but no properties are filled.

**Comment by ppekrol** [comment]
I've changed the following line in the EmailHttpRequest:

readonly Lazy<HttpBrowserCapabilitiesBase> browser = new Lazy<HttpBrowserCapabilitiesBase>(() => new HttpBrowserCapabilitiesWrapper(new HttpBrowserCapabilities() { Capabilities = HttpContext.Current.Request.Browser.Capabilities }));

it should work with both regular and Mobile views.

**Comment by andrewdavey** [comment]
@ppekrol's change has been added to `master`. Thanks!
