### ISSUE TITLE
Apostrophe in Email Address Throws Error

### ISSUE THREAD

**Issue by Pharylon** [andrewdavey/postal#123]
Apostrophes are valid in email addresses before the @ symbol (ie, mikeo'flanahan@someplaceirish.com). However, Postal is consistently throwing the following error when sending to such an email:

```
An invalid character was found in the mail header: ';'.
```

**Comment by andrewdavey** [comment]
Try escaping the email address. For example, `@Html.Raw(Model.ToEmailAddress)`

**Comment by Pharylon** [comment]
Thanks. That does, in fact, work.

**Comment by Pharylon** [comment]
I'm not sure this should be closed. This seems like a workaround for a bug still present.
