### ISSUE TITLE
Setting SMTP server

### ISSUE THREAD

**Issue by drewnoakes** [andrewdavey/postal#13]
I'd like to migrate to Postal.  My old approach has the SMTP server in config which is fine for me.  However it's not clear where to put this in code.

Before I had (in essence):  `new SmtpClient(Config.SmtpServer).Send(new MailMessage{...});`

It's not clear where I use this config setting in the documentation. The config you show doesn't mention an SMTP server at all.

Here's the error message:

```text
System.InvalidOperationException: The SMTP host was not specified.
   at System.Net.Mail.SmtpClient.CheckHostAndPort()
   at System.Net.Mail.SmtpClient.get_ServicePoint()
   at System.Net.Mail.SmtpClient.Dispose(Boolean disposing)
   at System.Net.Mail.SmtpClient.Dispose()
   at Postal.EmailService.Send(Email email)
   at Postal.Email.Send()
```

This'd be handy to have published in your docs.

Thanks for a great approach to sending emails with the MVC framework.

**Comment by andrewdavey** [comment]
One option is to configure the SmtpClient in your web.config file:

```
<configuration>
  <!-- Add the email settings to the <system.net> element -->
  <system.net>
    <mailSettings>
      <smtp>
        <network 
             host="relayServerHostname" 
             port="portNumber"
             userName="username"
             password="password" />
      </smtp>
    </mailSettings>
  </system.net>

  <system.web>
    ...
  </system.web>
</configuration>
```

Or do you need to create the SmtpClient object yourself?
In which case there is also way to support this in Postal. It's just a bit more code... Let me know if you need it.

**Comment by drewnoakes** [comment]
Thanks for that.  This form of the config was what I needed.

It would be helpful to link to the reference for this config from your documentation directly:

http://msdn.microsoft.com/en-us/library/w355a94k.aspx
http://msdn.microsoft.com/en-us/library/ms164240.aspx

**Comment by andrewdavey** [comment]
For those interested in the other approach I hinted at above:

```
var emailService = new EmailService(ViewEngines.Engines, null, () => CreateMySmtpClient());
```

Assuming you have some method called `CreateMySmtpClient` that returns an SmtpClient object.

**Comment by Edddy** [comment]
It worth commenting that this config:

```
 <system.net>
    <mailSettings>
      <smtp deliveryMethod="SpecifiedPickupDirectory" from="internal@internal.com.ar">
          <specifiedPickupDirectory pickupDirectoryLocation="d:\Temp\Mail" />
      </smtp>
   </mailSettings>
</system.net>
```

Gives an error "The SMTP host was not specified" (But the email is "sended" to the mail folder anyway)
To workaround this, you have to mention the network host, even when not used.

```
 <system.net>
   <mailSettings>
     <smtp deliveryMethod="SpecifiedPickupDirectory" from="internal@elisa.com.ar">
       <specifiedPickupDirectory pickupDirectoryLocation="d:\Temp\Mail" />
       <network
         host="localhost"
         port="25"
         defaultCredentials="true"
       />
     </smtp>
   </mailSettings>
 </system.net>
```
