### ISSUE TITLE
Views located in area view are not found by view engine

### ISSUE THREAD

**Issue by timdooling** [andrewdavey/postal#132]
I have an administrative view area and the view engine will not find any view located in the administrative area

I have determined the problem is in the location determined by UrlRoot().

This location only returns the root of the web application, not the current offset in the application, so it won't work for areas in mvc.

Is there any way this can be altered so that areas can be supported, such as adding an option to set a namespace or something similar to search for the view?

**Comment by hermanho** [comment]
https://github.com/zabeda/postal

**Comment by timdooling** [comment]
The below code is what we are using and it still does not work:

```
        dynamic email = new Email(mailViewModel.workingGroupName.Replace(" ", String.Empty));
        email.To = String.Join(",", memberListViewModelRepository.GetWorkingGroupEmail(mailViewModel.workingGroupName));
        if (String.IsNullOrEmpty(email.To))
        {
            return RedirectToAction("EmptyGroup");
        }

        email.Subject = mailViewModel.subject;

        email.MainBody = mailViewModel.mailMessage;
        email.AreaName = "AdminApplications.Areas.Administrator";
        email.Send();
```

What is the problem with our code?

**Comment by hermanho** [comment]
try

``` C#
dynamic email = new Email(mailViewModel.workingGroupName.Replace(" ", String.Empty), "Administrator");
```

**Comment by timdooling** [comment]
The compiler gives me an unknown constructor error and won’t compile.

**Comment by timdooling** [comment]
The constructor takes only one argument and two won't compile.

**Comment by hermanho** [comment]
Please get the source code from https://github.com/zabeda/postal and compile. This version is supported the area

**Comment by timdooling** [comment]
Yeah, I noticed that this branch was not merged to the main one.  The master branch does not have a multi-parameter constructor for Email.

I have compiled it and it does work.  A nugget package for this version would be helpful.
