### ISSUE TITLE
Content-Type resets to text/plain

### ISSUE THREAD

**Issue by jadiaz** [andrewdavey/postal#14]
no matter if I set the content-type: text/html the email message always reverts to text/plain. Is there a way to force text/html?

**Comment by andrewdavey** [comment]
Are you sending an email with only a HTML content, or HTML and plain text?

**Comment by jadiaz** [comment]
HTML and plain text. 

Jose

**Comment by andrewdavey** [comment]
And does the "header-only" view look something like this:

```
From: test@test.com
To: test@test.com
Subject: subject line
Views: Text, Html
```

Note the order of the Views header.

**Comment by jadiaz** [comment]
In the view I don't use Views: Text, HTML

I define Content-Type: text/HTML 

Jose

**Comment by andrewdavey** [comment]
Please look at the Multipart.\* files in https://github.com/andrewdavey/postal/tree/master/src/MvcSample/Views/Emails
They show how to work with multiple content types correctly. Note there are three files, one for the headers and two the actual contents.

**Comment by jadiaz** [comment]
If I just wanted to go with HTML I would still need to separate the header and content into two files?

Jose

**Comment by andrewdavey** [comment]
For only HTML, just create the one file with both headers and content.

**Comment by Edddy** [comment]
Andrew: could you please post an example of an HTML only file? I'm trying in several way with no luck

**Comment by andrewdavey** [comment]
@Edddy Here's an example for an HTML only email view. Sorry for the delay in getting back to you.

File: ~/Emails/Example.cshtml

```
To: test@test.com
From: example@website.com
Reply-To: another@website.com
Subject: @Model.Subject

<html>
    <body>
        <h1>HTML email</h1>
        <p>Hello, world</p>
        <p>Generated @Model.Date.ToShortDateString()</p>
    </body>
</html>
```

**Comment by Edddy** [comment]
So simple, thanks! (Sorry to bother you but I was trying with Content-Type: text/html; and other more complex schemas)

-----Original Message-----

**Comment by keithly** [comment]
I ran into this problem as well, and it was because I had left that comment "NOTE: There MUST be a blank line after the headers and before the content." between the headers and the opening html tag. Ooops.

**Comment by andrewdavey** [comment]
It sounds like the `if view output starts with "<"` code needs to tolerate leading white space, just in case there is comment first.

**Comment by andrewdavey** [comment]
v0.6.3 trims white space from the email body. It should still detect HTML when there is a Razor comment before the `<html>` starts.
