### ISSUE TITLE
Embedding images in HTML email

### ISSUE THREAD

**Issue by drewnoakes** [andrewdavey/postal#15]
This page has a nice writeup:

http://www.systemnetmail.com/faq/4.4.aspx

So, instead of linking to images using <img src="href://site/path"> I'd like to embed them and use <img src="cid:contentId">.

Is this possible using Postal?

**Comment by andrewdavey** [comment]
Yes.
See https://github.com/andrewdavey/postal/blob/master/src/MvcSample/Views/Emails/Multipart.Html.cshtml for an example of embedding and image.

**Comment by drewnoakes** [comment]
Looks fantastic, thanks very much.  As elegant as I've come to expect from and enjoy of this API.
