### ISSUE TITLE
Sample For Postal.AspnetCore?

### ISSUE THREAD

**Issue by epozsh** [andrewdavey/postal#175]
Hello,

is there any sample for Asp.Net Core MVC

**Comment by hermanho** [comment]
https://github.com/hermanho/postal.aspnetcore.samples

**Comment by huseyingoztok** [comment]
How to inject IEmailService in .net core 3.1. Please give me example @andrewdavey @hermanho  I am using autofac

**Comment by hermanho** [comment]
Hi @huseyingoztok, you would need to implement the types registration in autofac. Here is the code in asp.net core DI.
https://github.com/hermanho/postal.aspnetcore/blob/674bfcf333e8d32f3d304ba43343418198f6f864/src/Postal.AspNetCore/ServiceCollectionExtensions.cs#L15
https://github.com/hermanho/postal.aspnetcore.samples/blob/881e13618d2c28e650c682e951beb253e65afe4c/WebSample/Startup.cs#L32
