### ISSUE TITLE
Postal doesnt work with mailgun and postmarkapp

### ISSUE THREAD

**Issue by ryudice** [andrewdavey/postal#19]
This service reject email sent with postal using SMTP.

**Comment by andrewdavey** [comment]
Can you be more specific about what does not work please?

**Comment by ryudice** [comment]
Hello, sorry for the language on my post, I was upset and a little bit drunk, for some strange reason services like mailgun and postmarkapp reject emails sent with postal, I have yet to find why since they dont even appear on the log, I started working on a patch to make postal use the rest api of this services, I will gladly fork it if you are ok with these feature been included.

**Comment by andrewdavey** [comment]
Thanks for amending the issue :)

I've not used those services myself, so please do provide any info you can. Do they allow sending of email via a regular SMTP connection? What does your web.config look like for the mail settings?

(and as always, patches are very welcome.)

**Comment by brgrz** [comment]
actually MailGun accepts emails from Postal just fine, I've been using it for a few months now

**Comment by benwmills** [comment]
Just an FYI that sending mail via Postmark using Postal seems to work just fine.
