### ISSUE TITLE
Wrong encoding when there are latin characters in the email view

### ISSUE THREAD

**Issue by velum** [andrewdavey/postal#21]
If there are some accentuated (àäéèç...) characters in an email view, then the Content-Transfer-Encoding switches to base64 (instead of quoted-printable), and the email becomes unreadable.

You can do a test with the following view:

To: your@email.com
From: some@email.com
Subject: Grüß Dich!

Comment ça va?

Hence it is not possible to send plain text emails in languages using accentuated characters (basically languages other than English).

A workaround is to provide the email in both plain text and html, as specified on https://github.com/andrewdavey/postal/wiki/Multiple-Alternative-Views, and to specify utf-8 as character set in the views:

Content-Type: text/plain charset=utf-8
and
Content-Type: text/html; charset=utf-8

Beware also of the syntax. In the examples, Viewbag should be spelled ViewBag with a capital B. 

If the charset is not specified, the charset that will appear in the email messages will be utf-16, and the messages won't be readable. All I see are chinese characters in that case.

UPDATE: However, I just discovered that this workaround won't fix subject lines. If a subject line contains accentuated characters, it won't get encoded properly, and it will be garbled.

**Comment by andrewdavey** [comment]
Example fixed.
Looking into the encoding issue now.

**Comment by andrewdavey** [comment]
In the simple email body case (not multipart) are you saying that the email does not render correctly in your email client?
Or are you saying that you don't like the base-64 encoding?

Non-ascii characters are generating emails that render fine for me in Windows Live Mail.
Can you perhaps send me an example .eml file to andrew@equin.co.uk so I can take a look? Thanks.

**Comment by tah91** [comment]
had the same pb
it works if you do 

```
@Html.Raw(myStringWithAccent)
```

**Comment by andrewdavey** [comment]
Calling `@Html.Raw(...)` does seem to be the way to fix this issue. Kind of annoying perhaps. Let me know if anyone finds a simpler solution.

**Comment by quedicesebas** [comment]
What about using postal outside ASP.NET...how to fix this?
My email view:

@model dynamic

Content-Type: text/html; charset=utf-8
To: @Model.Notification.ToUser.Name @Model.Notification.ToUser.Email
From: Hobbule no-reply@hobbule.com
Subject: @Model.Notification.FromUser.Name @Model.NotificationDisplay @Model.Notification.Activity.Name

<html lang="@System.Globalization.CultureInfo.CurrentUICulture.Name">
<body>
    @Model.Notification.FromUser.Name @Model.NotificationDisplay @Model.Notification.Activity.Name
</body>
</html>

I getting problems with latin characters only header (to name and subject), in the email body don't

**Comment by TimurZanagar** [comment]
@sebrojas14 Do you've a solution for this problem?
@andrewdavey This issue still exists. Any idea?
