### ISSUE TITLE
Recompile required to "refresh" views when used outside of MVC app

### ISSUE THREAD

**Issue by jslaybaugh** [andrewdavey/postal#22]
I'm using Postal in a class library project (being called from a MVC app, but shared by several MVC apps) and the email content files are in a separate /Templates folder and when I change the .cshtml view files and then save, I have to change a line of code and re-compile and then change it back before the changes are picked up.  I assume there is some filewatcher or something there that caches the templates, but it doesnt appear to be working properly if its not within the MVC App (although since I'm not using it inside the MVC app, i can't say that definitively).

NOTE, in the current scenario, i'm using Multi-part (text/html) views, but it appears to not be specific to that model.  I went back to just a pure single HTML view and the changes are still not picked up on save.

File structure:
- Project
  - API (MVC app)
  - Web (MVC app)
  - Templates
    - cshtml views (UserInviteNew.cshtml, UserInviteNew.Html.cshtml, and UserInviteNew.Text.cshtml) are here.

Sample code:

```
    public static bool SendNewUserInvite(HttpContextBase context, NewUserInvite modelData)
    {
        try
        {
            var viewsPath = GetEmailTemplatesPath(context);

            var engines = new ViewEngineCollection();
            engines.Add(new FileSystemRazorViewEngine(viewsPath));

            var service = new EmailService(engines);

            dynamic email = new Email("UserInviteNew");
            email.Values = modelData;
            service.Send(email);

            return true;
        }
        catch (Exception ex)
        {
            Logger.Fatal(ex.Message, ex);
            return false;
        }
    }
    private static string GetEmailTemplatesPath(HttpContextBase context)
    {
        var root = context.Server.MapPath("~/");
        if (root.EndsWith(@"\")) root = root.Substring(0, root.Length - 1);
        var upOne = root.Substring(0, root.LastIndexOf('\\'));
        return upOne + @"\Templates";
    }
```

**Comment by andrewdavey** [comment]
I'll have to dig into what the RazorEngine is doing under the covers... Postal isn't doing any file system watching itself.

**Comment by jslaybaugh** [comment]
OK.  I did some quick searching at their codeplex site (http://razorengine.codeplex.com/discussions?searchText=compil&size=10&page=3) and from what I can infer from them it definitely seems like the views are compiled and that would explain why they aren't changing on save (I guess most people use it with hardcoded strings rather than external files).  

Some of those threads mention manual `.Compile()` methods, and I even found a overload of `FileSystemRazorViewEngine.FindView()` that accepted a `bool useCache` parameter, and while those seem like they would be helpful, when I poked around in the Postal source, I couldn't really see where something like that would be added.  I'd offer to do a pull request and make an attempt at patching it up, but I really don't have the time at this point in the project to dive around in Postal.  So, if that's all it is and you can quickly make sense of something that would force the recompilation of external files, that'd be awesome.  If it's more complicated than that, I might just have to look for another solution because we won't necessarily be able to recompile every time my designer changes some email content.

Thanks!

**Comment by andrewdavey** [comment]
I think this is an issue with the RazorEngine library. I created an issue on that project:
http://razorengine.codeplex.com/workitem/492

It seems to cache the result of the template parse. I hope they'll provide a work around I can put into Postal.

**Comment by andrewdavey** [comment]
I think I've figured out a fix. Please try pulling latest from master branch.

It now includes the file last write time in the RazorEngine cache key. So changing the file will result in a new parse happening.

**Comment by jslaybaugh** [comment]
It seems to work when I pull from master and manually add the .dll reference.  When I just did Update-Package with NuGet, it said it was at 0.6.3 also, but it didnt seem to work.  Maybe it was just me...either way its working now. Thanks!

**Comment by andrewdavey** [comment]
I'll need to update the Postal nuget package soon to include the fix.

Re-opening until fix is live.
