### ISSUE TITLE
Multi-Part messages render as base64 junk/chinese chars when used outside MVC App

### ISSUE THREAD

**Issue by jslaybaugh** [andrewdavey/postal#23]
I'm using Postal in a class library project (being called from a MVC app, but shared by several MVC apps) and the email content files are in a separate /Templates folder. It seems to work fine if I have just a HTML OR Text only view (UserInviteNew.cshtml), but when I attempt to do the multi-part MIME, it goes haywire.

**File structure:**
- Project
  - API (MVC app)
  - Web (MVC app)
  - Templates
    - cshtml views (UserInviteNew.cshtml, UserInviteNew.Html.cshtml, and UserInviteNew.Text.cshtml) are here.

**Sample code:**

```
    public static bool SendNewUserInvite(HttpContextBase context, NewUserInvite modelData)
    {
        try
        {
            var viewsPath = GetEmailTemplatesPath(context);

            var engines = new ViewEngineCollection();
            engines.Add(new FileSystemRazorViewEngine(viewsPath));

            var service = new EmailService(engines);

            dynamic email = new Email("UserInviteNew");
            email.Values = modelData;
            service.Send(email);

            return true;
        }
        catch (Exception ex)
        {
            Logger.Fatal(ex.Message, ex);
            return false;
        }
    }

    private static string GetEmailTemplatesPath(HttpContextBase context)
    {
        var root = context.Server.MapPath("~/");
        if (root.EndsWith(@"\")) root = root.Substring(0, root.Length - 1);
        var upOne = root.Substring(0, root.LastIndexOf('\\'));
        return upOne + @"\Templates";
    }
```

**Views:**

UserInviteNew.cshtml:

```
To: @Model.Values.Email
From: no-reply@pathwayapp.com
Subject: You've been invited to Pathway!
Views: Text, Html
```

UserInviteNew.Html.cshtml

```
Content-Type: text/html; charset=utf-8

<h2>Hey there, @Model.Values.FirstName!</h2>
<p>You've been invited to use Pathway -- the leading church communication tool!!!</p>
<p>To accept your invitation and set up your profile, please visit the following link: <a href="http://test.com/pathway/web/accounts/AcceptInvite?code=@Model.Values.UserName">Accept Invitation</a>.</p>
<p>See you soon!</p>
```

UserInviteNew.Text.cshtml

```
Content-Type: text/plain; charset=utf-8

Hey there, @Model.Values.FirstName!

You've been invited to use Pathway -- the leading church communication tool!

To accept your invitation and set up your profile, please visit the following link: http://jslaybaugh.homeip.net/pathway/web/accounts/AcceptInvite?code=@Model.Values.UserName

See you soon!
```

**And here is the output of the mail message:**

```
X-Sender: no-reply@pathwayapp.com
X-Receiver: jslaybaugh@gmail.com
MIME-Version: 1.0
From: no-reply@pathwayapp.com
To: jslaybaugh@gmail.com
Date: 23 Aug 2011 17:05:20 -0500
Subject: You've been invited to Pathway!
Content-Type: multipart/alternative;
 boundary=--boundary_0_570ffc34-3d93-4836-8f44-065fc11742d4


----boundary_0_570ffc34-3d93-4836-8f44-065fc11742d4
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: base64

SGV5IHRoZXJlLCBKb3JpbiENCg0KWW91J3ZlIGJlZW4gaW52aXRlZCB0byB1c2Ug
UGF0aHdheSAtLSB0aGUgbGVhZGluZyBjaHVyY2ggY29tbXVuaWNhdGlvbiB0b29s
IQ0KDQpUbyBhY2NlcHQgeW91ciBpbnZpdGF0aW9uIGFuZCBzZXQgdXAgeW91ciBw
cm9maWxlLCBwbGVhc2UgdmlzaXQgdGhlIGZvbGxvd2luZyBsaW5rOiBodHRwOi8v
anNsYXliYXVnaC5ob21laXAubmV0L3BhdGh3YXkvd2ViL2FjY291bnRzL0FjY2Vw
dEludml0ZT9jb2RlPWpvcmlubWljaGFlbHNsYXliYXVnaDMNCg0KU2VlIHlvdSBz
b29uIQ0K
----boundary_0_570ffc34-3d93-4836-8f44-065fc11742d4
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: base64

PGgyPkhleSB0aGVyZSwgSm9yaW4hPC9oMj4NCg0KPHA+WW91J3ZlIGJlZW4gaW52
aXRlZCB0byB1c2UgUGF0aHdheSAtLSB0aGUgbGVhZGluZyBjaHVyY2ggY29tbXVu
aWNhdGlvbiB0b29sISEhPC9wPg0KDQo8cD5UbyBhY2NlcHQgeW91ciBpbnZpdGF0
aW9uIGFuZCBzZXQgdXAgeW91ciBwcm9maWxlLCBwbGVhc2UgdmlzaXQgdGhlIGZv
bGxvd2luZyBsaW5rOiA8YSBocmVmPSJodHRwOi8vanNsYXliYXVnaC5ob21laXAu
bmV0L3BhdGh3YXkvd2ViL2FjY291bnRzL0FjY2VwdEludml0ZT9jb2RlPWpvcmlu
bWljaGFlbHNsYXliYXVnaDMiPkFjY2VwdCBJbnZpdGF0aW9uPC9hPi48L3A+DQoN
CjxwPlNlZSB5b3Ugc29vbiE8L3A+DQo=
----boundary_0_570ffc34-3d93-4836-8f44-065fc11742d4--
```

(in windows mail viewer, this renders as a bunch of chinese characters).

Not sure what I could be doing wrong here. I've even specified the encoding charset.  Somehow, its gets base64 encoded and the `Content-Transfer-Encoding` header gets set to `base64`!

My only guess is that it has something to do with the `FileSystemRazorViewEngine` but I'm trying to implement this in a production project that is getting close to wrapping up and going live, so hopefully there is a solution.

Thanks,

Jorin

**Comment by andrewdavey** [comment]
It would be useful to know if it is the `FileSystemRazorViewEngine` that is causing the encoding problem. Are you able to switch to the default view engine (copy the email views into the web project) to test?
I will try to look into this properly this evening for you.

**Comment by jslaybaugh** [comment]
So, I'm not an expert on MIME multipart at all, but from what I'm reading this morning it appears this is what it's _supposed_ to be doing.

I recompiled and tested it again this morning and the output was still base 64 encoded, but this time when I opened it with outlook, it printed fine -- no chinese characters.  My guess is that adding the `charset=utf-8` like I did is what fixed it, but as i mentioned in the other issue i submitted, the file wasnt getting re-loaded properly, so it was still pulling it without the UTF-8 and hence the chinese characters.

However, I've been clicking on "show original" on some gmail messages that have come in as multipart in order to see how this is normally done.  It appears from my quick observations, that you should be able to specify `Content-Transfer-Encoding: 7bit` and actually send it through as human readable HTML/text.  However, when I try to add that header to the .Text.cshtml file and the .Html.cshtml files, right below the `Content-Type` header, it still gets overwritten to base64 and something somewhere does the base64 encoding regardless.

In the end, I'm probably OK with it doing the base64 encoding as long as I know that all email clients can read that. If it is a defined part of the MIME standard and all email clients know what to do with it, then we're good to go, but i'm not 100% sure that is the case and can't seem to find anywhere that states that is the case.

**Comment by andrewdavey** [comment]
I copied your example email output into notepad and saved as a UTF-8 ".eml" file. The file then opens fine in Windows Live Mail. Saving as ANSI also works. Saving as Unicode results in a blank screen when opened - no random characters for me though.

Can you send me a sample .eml file to andrew@equin.co.uk? I'll need to have a look at the actual file output. Thanks.

**Comment by andrewdavey** [comment]
Just saw your reply - so don't worry about sending the file.

**Comment by jslaybaugh** [comment]
I guess, according to this: http://email.about.com/cs/standards/a/base64_encoding.htm, base64 is used to boil UTF encoded text down to ASCII because thats all email was designed handle, so that makes sense and seems like it should work for all email clients, so I guess there is really no bug here.

However, as a _feature request_ it might be nice if we could somehow override the base64 process and instead tell it to just keep it as plain ASCII or ISO-8859-1 or something for messages that we know are only using that charset.  This would save it the overhead of doing the base64 encode and also make sure that clients who don't know how to decode would get the text as it was intended.

Thanks!

**Comment by andrewdavey** [comment]
Postal is not explicitly setting base64 encoding. I think it happens automatically inside .NET's MailMessage class when creating a multipart message.
I'm not am expert in mail client support either. I would think that base64 should be fine.

I will look into the encoding options to see if base64 can be disabled.
