### ISSUE TITLE
Display name of the MailAddress class support?

### ISSUE THREAD

**Issue by brgrz** [andrewdavey/postal#24]
I've been watching your screencast and I've read the wiki's and blog but can't seem to find how to support display names. Now the .NET's MailAddress class does support proving both the display name and the email address to the constructor. 

I would like to be able to specify the display name for the emails I sent because it looks better and friendlier and it might even bypass a bit higher number of antispam filters than when just specifying the email address.

Is it possible?

**Comment by andrewdavey** [comment]
Try just putting the name before the email address, separated by a space.

```
To: John Smith john@smith.com
From: Bob Green bob@green.com
Subject: test

hello
```

If generating the name from a variable:

```
To: @ViewBag.Name @ViewBag.EmailAddress
```

**Comment by jslaybaugh** [comment]
Works for me. Awesome!
