### ISSUE TITLE
Attachments don't work on iphone/ipad

### ISSUE THREAD

**Issue by dsghi** [andrewdavey/postal#29]
I'm working on a site and I need to send attachments to iphone/ipad users because safari doesn't support the file type for download. The issue I have, is that the attachments show up inline at the end of the message. I don't know if it's something I'm doing wrong, or a bug of some kind. On my desktop I use Outlook with Exchange, I've tested in windows phone 7, andriod, windows live, and Gmail. All receive the attachement correctly. Anyone else run into this, or have any suggestions?

**Comment by dsghi** [comment]
It's definitely something to do with formatting the attachment I think. If I send the attachment to my desktop email, then manually download it, compose a new message in outlook, attach the file, and then send it to my ipad, I receive the attachement as expected.

**Comment by andrewdavey** [comment]
What type of file are you attaching?

If you send an email using the .NET SmtpClient and MailMessage classes (which Postal uses itself) do you get a correct email? I need to know if this is a .NET issue or something specific that Postal is doing wrong.

**Comment by dsghi** [comment]
Ah I didn't think to try that, I'll give it a shot. The attachment is a VCF file.

**Comment by dsghi** [comment]
OK, so it does work using SmtpClient if I attach the file without specifying the content type, such as:             message.Attachments.Add(new Attachment("C:\file.vcf")); that gives it a Content-Type: application/octet-stream. 

I looked on the email I'm generating with postal and I'm ending up with a Content-Type of text/x-vcard, which is technically correct, but obviously a problem for apple email lol. I'm not sure where that's getting set, is that being set by Postal? I'm attaching in postal using a memory stream, and only passing in the name: Attachments.Add(vcfName, memoryStream.ToArray());

**Comment by dsghi** [comment]
I wanted to make sure it wasn't something with my vcf library, so I've tried using the same code to generate the attachment with smtpclient, and the content-type remains application/octet-stream if I don't explicitly set it. So at this point, it's got to be something with postal. Is there any option for explicitly setting the content-type of an attachment in Postal? I'm looking through the source, but not seeing anything... Thanks for the help, btw :)

**Comment by andrewdavey** [comment]
Cassette doesn't really do any processing of attachments. It simply adds them to the generated `MailMessage` class. So I don't understand why you're getting different content types.

Can you try specifying the content type when creating the attachment:

```
email.Attach(new Attachment(stream, fileName, "application/octet-stream"));
```

Does this force the right content type?

**Comment by dsghi** [comment]
It's working fine, I'm just a moron, and didn't realize there was a difference in code between my production site where the issue was occuring and my dev enviroment, where it's working perfectly. So there's no problem with your code. Also for future reference, it is possible to set any arbitrary content type using the code you suggested. Thanks again for your help, sorry it turned out to be a mistake lol!

**Comment by andrewdavey** [comment]
No worries :) I'm glad you've solved it!

My guess about the differing environments is that either the Windows registry or IIS has a mapping of file extensions to content types. So your production server must have an entry for `vcf` files.

**Comment by dsghi** [comment]
You haven't by chance tried working with this in .net 4.5 or MVC 4 yet have you? I've been playing with the developer preview and I'm really excited for the mobile view support. The only reason I'm asking, is I loaded postal and I'm getting an unimplemented exception when I try to send. I can't tell if it's something just not yet complete in .net 4.5 or something no longer availible.

**Comment by andrewdavey** [comment]
I've not tried .NET 4.5 yet. Can you paste in the stack trace into a new GitHub issue please? I'm guessing it's one of the System.Web.Http*Base classes, which Postal overrides, missing something used by 4.5.
Thanks.
