### ISSUE TITLE
Improper parsing of email address

### ISSUE THREAD

**Issue by jwidmer** [andrewdavey/postal#33]
The "To" header written like:
To: @ViewBag.ToDisplayName @ViewBag.ToEmail
will not work with an email address such as:
"Smith, Bob" bob@smith.com
It appears that the comma in "Smith, Bob" is parsed as if this is multiple email addresses throwing an exception:
The specified string is not in the form required for an e-mail address.

**Comment by tomdenny** [comment]
Your issue is a month old and probably solved.  But I did confirm just now that this works fine.  I think the problem is comma's need to be quoted for the .NET SMTP Client.  So:
To: "@ViewBag.ToDisplayName" @ViewBag.ToEmail
instead of
To: @ViewBag.ToDisplayName @ViewBag.ToEmail
