### ISSUE TITLE
How to send using a gmail address? It asks me for SSL yet I don't see how to use SSL.

### ISSUE THREAD

**Issue by sergiotapia** [andrewdavey/postal#45]
Hi Andrew, thanks for the help.

I'm trying to send out an email from my gmail acccount:

```
dynamic email = new Email("Appointment");
email.EnableSsl = true;
email.To = "sergiotapia@outlook.com";
email.Send();
```

And I get this error:

> System.Net.Mail.SmtpException: {"The SMTP server requires a secure connection or the 
> client was not authenticated.The server response was: 5.7.0 Must issue a STARTTLS command first. 

Any ideas what I need to do to send this email out?

Here's my web.config setting:

```
<system.net>
    <mailSettings>
        <smtp deliveryMethod="Network" from="hello@dentist.ly.com">
        <network host="smtp.gmail.com" port="587" defaultCredentials="false" userName="hello@dentist.ly" password="newyear2012" />
        </smtp>
    </mailSettings>
</system.net>
```

**Comment by andrewdavey** [comment]
Can you try enabling SSL in web.config? http://theoldsewingfactory.com/2011/01/06/enable-ssl-in-web-config-for-smtpclient/

**Comment by sergiotapia** [comment]
Thanks Andrew! Your projects are so damn useful! :+1: 

I just needed to add `enableSsl="true"` to my `web.config` file. Maybe the official project page could mention this for future people who might have trouble sending with gmail?
