### ISSUE TITLE
_ViewStart superfluous

### ISSUE THREAD

**Issue by breyed** [andrewdavey/postal#48]
As far as I can tell, the _ViewStart.cshtml that lives next to the .cshtml files for the email messages serves no purpose and can be removed.

**Comment by andrewdavey** [comment]
This is to override the `Layout` property, often set by `~/Views/_ViewStart.cshtml`. Otherwise email views would have the same layout as the page views of your application.

**Comment by breyed** [comment]
Sorry, you're right. For some reason, my email views had their own `@{ Layout = null; }` lines. Those lines were the real superfluosities.
