### ISSUE TITLE
Wrong Email Encoding

### ISSUE THREAD

**Issue by escobar5** [andrewdavey/postal#51]
When I'm sending emails through postal they are being displayed with a wrong encoding, I get a bunch of chinnese characters.

Is there a way to set the encoding?

Thanks

**Comment by andrewdavey** [comment]
Try setting the char set in the content type header of the email:

```
Content-Type: text/plain; charset=utf-8

This is the message body...
```

**Comment by escobar5** [comment]
Sorry for the delay, that worked.

Thanks
