### ISSUE TITLE
Using custom Model without inheriting from Email?

### ISSUE THREAD

**Issue by NightOwl888** [andrewdavey/postal#52]
Good work on this project - it seems to do everything I am looking for - multi-part emails, sending from class libraries, rendering the views as strings. There is only one exception - I have Model classes implemented in the CSLA framework, which means they must inherit from one of the CSLA base classes. And C# doesn't allow multiple inheritance, so I am stuck having to copy all of my data to another object just to send the email so I can inherit from Email.

At least I think - I don't see a way to attach an external model like you can in MvcMailer or FluentEmail, but both of those packages have other limitations as well. 

I like postal the best of the 3 because you seem to have separated concerns better and allowed for DI support, but I need to be able to use my existing model classes rather than reinvent the wheel.

FluentEmail uses a [template driven system] that I really like (that has both a razor and markdown parser), but no multi-part support is a deal breaker. 

In case I missed it, is using a custom model supported without requiring any inheritance?  If not, what is your opinion of adding some support similar to FluentEmail to supply a model?

**Comment by andrewdavey** [comment]
Would you like to take on this enhancement? I'd happily accept a pull request.

Extract a new `IEmail` interface from the `Email` class. It would need the following members

```
string ViewName { get; set; }
ViewDataDictionary ViewData { get; set; }
IList<Attachment> Attachments { get; set; }
```

Then replace most occurrences of `Email` with `IEmail` in the project.

That should provide the ability to implement `IEmail` on your own model classes.

**Comment by NightOwl888** [comment]
Thanks for the info. I am on the fence whether to use this solution or build my own brew.

I have several requirements that no package seems to support out of the box (at least not all together), and many packages don't have very good extensibility.
1. Database driven views
2. Layout views per tenant (templates)
3. "View this email in your browser" functionality
4. Strongly typed models (preferred)
5. Ability to email from background processes

I am thinking for that last one to just make the template engine pluggable so I can put in the XSLT based email system I already have in the case of background processes or else just exposing the email service as a web service so it can be executed externally.

While #2 isn't an absolute requirement, it could save a ton of work later if I need to re-theme one of the sites, which has me looking in the direction of MvcMailer.

Another idea I am toying with is ensuring that the template engine and message engine are separate, replaceable pieces. So, for example you could potentially replace the mail service with a text message service.

Anyway, I haven't started this project yet and it is not currently at the top of the stack, so I will take another look at my options and give it some more thought.

**Comment by andrewdavey** [comment]
Postal can send emails from a non-web process, see https://github.com/andrewdavey/postal/wiki/Postal-in-non-web-scenario

It should be possible to support layouts as well, even when using the `FileSystemRazorViewEngine`. I think you just have to set `_Layout`.

Still, if Postal doesn't do everything you need, feel free to fork the project, or even just grab any code you find useful :)
