### ISSUE TITLE
Issue with Razor3 and MVC5

### ISSUE THREAD

**Issue by chouteau** [andrewdavey/postal#55]
I have an "not implemented exception" with Razor3 and MVC5  if view use RouteUrl like :

@Url.RouteUrl(...);

Resolution :

Override GetService in MockHttpContext

public override object GetService(Type serviceType)
{
    var result =  System.Web.Mvc.DependencyResolver.Current.GetService(serviceType);
    return result;
}

It resolve the System.Web.HttpWorkerRequest service required

**Comment by chouteau** [comment]
Using EmailViewRender with background thread cause an exception with browser capabilities

Resolution :

Replace CreateHttpBrowserCapabilities in EmailHttpRequest class like

HttpBrowserCapabilitiesWrapper CreateHttpBrowserCapabilities()
{
    var factory = new System.Web.Configuration.BrowserCapabilitiesFactory();
    var browserCapabilities = new HttpBrowserCapabilities();
    if (HttpContext.Current != null)
    {
        browserCapabilities.Capabilities = HttpContext.Current.Request.Browser.Capabilities;
    }
    else
    {
        browserCapabilities.Capabilities = new Hashtable 
        { 
            { string.Empty, UserAgent } 
        };
    }
    factory.ConfigureBrowserCapabilities(new NameValueCollection(), browserCapabilities);
    return new HttpBrowserCapabilitiesWrapper(browserCapabilities);
}

**Comment by andrewdavey** [comment]
Postal v0.9.0 removed the custom `EmailHttpRequest` class. Can you give it a try and let me know if it's working for you please?
