### ISSUE TITLE
Localization for e-mails

### ISSUE THREAD

**Issue by djanosik** [andrewdavey/postal#57]
Hi,

I think it would be nice if we could use some conventions to localize e-mails. For example if we could create views with names similar to *.resx files:
- Views/Emails/Email.cshtml
- Views/Emails/Email.**en-US**.cshtml
- Views/Emails/Email.**de-DE**.cshtml

Or:
- Views/Emails/**en-US**/Email.cshtml
- Views/Emails/**de-DE**/Email.cshtml

I prefer the second approach. What do you think?

Thank you!

**Comment by darcythomas** [comment]
You would need to to choose the culture for the user you are sending to (which may not be what the current thread culture)

You could just create:
- Views/Emails/Email-en-US.cshtml
- Views/Emails/Email-de-DE.cshtml

Then in the controller call:
-    dynamic email = new Email("Email-en-US");
-    dynamic email = new Email("Email-de-DE");
