### ISSUE TITLE
How to set from address programatically

### ISSUE THREAD

**Issue by Lakshmipathijp** [andrewdavey/postal#62]
Hi,

I have a requirement, razor view specifies only message(body), rest all for example To, CC, From, Subject will be set in controller,
I am getting "A from address must be specified"

Please suggest, Thanks in advance..

Lp

**Comment by andrewdavey** [comment]
Postal does require the email headers to be in the view. So I don't think it'll work for your requirement.

**Comment by Lakshmipathijp** [comment]
Hi,

Thanks a lot for the quick response.

Lp
