### ISSUE TITLE
Send emails in background inside ASP.NET MVC application

### ISSUE THREAD

**Issue by odinserj** [andrewdavey/postal#71]
I think it will be interesting for anyone – a **reliable** way to send emails **in background** inside ASP.NET MVC application, without external web services or recurring tasks, using **Postal** and [**HangFire**](http://hangfire.io). 

[Here is the tutorial](http://docs.hangfire.io/en/latest/tutorials/send-email.html).

**Comment by andrewdavey** [comment]
Very nice! HangFire looks awesome.
