### ISSUE TITLE
Automatic upgrade

### ISSUE THREAD

**Issue by p10tyr** [andrewdavey/postal#78]
Can you make it clear that installing the latest version will install the latest DLL's used to run with latest Postal even if using older MVC. Possibly include links to MVC 3 ,4.5 and 5 cause its a nightmare reverting (and trust me reverting is easier than trying to upgrade MVC) 

This is not the first time I quickly installed Postal and then realised it dumped new DLL's breaking my entire site and causing me endless grief.
I spent way too many hours with YSOD because of this :(

**Comment by andrewdavey** [comment]
There are specific packages for MVC 3, 4 and 5 now e.g. `Postal.Mvc5` . I've de-listing the old `Postal` package from Nuget.

Which package were you using?

**Comment by p10tyr** [comment]
Yea I went to Nuget and searched for Postal. It was simple to change the 5 to 4. Your website only shows example of 5 and does notot mention to install 4 or 3 to the target framework. I know its not your fault, VS just goes and replaces the DLL's and every thing breaks. Just thought you might want to warn people because without source control its a nightmare to fix. ;(

**Comment by p10tyr** [comment]
While looking for some help on something custom with POstal I ran into this guy who also has the same issue.

http://stackoverflow.com/questions/24223421/postal-for-asp-mvc-4-wants-me-to-use-mvc-5
