### ISSUE TITLE
use of special character

### ISSUE THREAD

**Issue by mcaradec** [andrewdavey/postal#8]
Hi, I am using  Postal in my mailing application and I encountered a problem with the encoding of special characters.
is it possible to use special characters  into a Postal application and how ?
thanks

**Comment by andrewdavey** [comment]
Can you give an example of the characters that are not being correctly displayed please?
What are you seeing instead?

**Comment by mcaradec** [comment]
I use characters like é and  è (french characters)  , and i see    &#233; and &#232;  in the  mail .

**Comment by mcaradec** [comment]
i see "& # 2 3 3 ; " and  "& # 2 3 2 ; " in the mail

**Comment by andrewdavey** [comment]
Are you creating plain text or HTML emails?

**Comment by andrewdavey** [comment]
Ah, try changing the content type of your HTML email view to this:
Content-Type: text/html; charset=utf-8

i.e. specifying the charset

**Comment by mcaradec** [comment]
I will try, i keep you updated, thanks again

**Comment by mcaradec** [comment]
It works, but is it possible to do this with a plain text email?

**Comment by mcaradec** [comment]
Hi, i tried to define a charset into a plain text email or  encode the viewbag.Message but nothing works, do you have an idea about this ?

**Comment by andrewdavey** [comment]
Can you configure web.config to save emails to a directory and then take a look at the generated ".eml" file?
Paste the contents of the file into a comment here please. I can then see what headers are being generated and the encoding. Thanks.

**Comment by mcaradec** [comment]
below the content of the file, the content inside the viewbag is not displayed properly. However if I put an "é" into the view , it displays well 

X-Sender: demo@cma-cgm.com
X-Receiver: demo@cma-cgm.com
MIME-Version: 1.0
From: demo@cma-cgm.com
To: demo@cma-cgm.com
Date: 11 May 2011 15:24:06 +0200
Subject: Important Message
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: base64

DQpIZWxsbywNCg0KTWVzc2FnZTogJiMyMzM7dmFkZXINCg0KQ29yZGlhbGVtZW50
LA0KRMOpbW8NCg==

And the result in outlook :

Hello,
Message: & # 2 3 3 ; vader
Cordialement,
Démo

**Comment by andrewdavey** [comment]
Thanks. Can you paste in the view page as well? I'm trying to work out why it's generating an HTML entity. I don't see that happening at my end.

**Comment by mcaradec** [comment]
my view page : 

To: demo@cma-cgm.com
From: demo@cma-cgm.com
Subject: Important Message

Hello,

Message: @ViewBag.Message

Cordialement,
Démo

**Comment by andrewdavey** [comment]
Ah I see!
Try:
@Html.Raw(ViewBag.Message)

By default @somevar will HTML encode the string.

**Comment by mcaradec** [comment]
It works !!!!
thanks again for your help

**Comment by MortenChristiansen** [comment]
Just a little tip to avoid this for all your email templates (it does require you to put your email templates outside the views folder with its own razor web.config, unless you want to disable html encoding in all your views). You can make all your email views inherit from a custom class that does not html-encode variables. Something like this:

```
public abstract class EmailTemplateView<TModel> : WebViewPage<TModel>
{
    public override void Write(object value)
    {
        WriteLiteral(value);
    }
}
```

Then change the view base-class in the razor web.config file in the email templates folder:

```
<pages pageBaseType="mynamespace.EmailTemplateView">
```

This will stop encoding of all your emails so be careful if you also have html emails. I don't know if there is a clean way to either have a different base class for html emails or to detect the format inside the custom view class.

**Comment by andrewdavey** [comment]
@clone1985 Thanks for the awesome tip!
There may be a way for Postal to tell the view it's rendering plain text and toggle the behaviour of Write accordingly.
