### ISSUE TITLE
Postal.Mvc4 nuspec file references lower version of RazorEngine than project references

### ISSUE THREAD

**Issue by jcgillespie** [andrewdavey/postal#83]
`Postal.Mvc4.nuspec` has the `RazorEngine` dependency version ranged from `(2.1.-3.0]`, but the `Postal.Mvc4` project references `RazorEngine` version `3.3.0`.

This is causing exceptions like 
System.IO.FileLoadException: Could not load file or assembly 'RazorEngine, Version=3.3.0.0, Culture=neutral, PublicKeyToken=9ee697374c7e744a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

**Comment by andrewdavey** [comment]
Nice one! Thanks.

**Comment by jcgillespie** [comment]
No problem. Thanks for the awesome work. Do you think this will get published to NuGet soon?

**Comment by andrewdavey** [comment]
It's in Nuget now :)
