### ISSUE TITLE
Previewing emails in MVC4

### ISSUE THREAD

**Issue by plmeister** [andrewdavey/postal#85]
Hi Andrew,

really liking postal so far, added it to my project last night and was generating emails within minutes - very easy to use..

it looks as though you're missing EmailViewResult.cs from your MVC4 project though, so I can't preview emails as shown in your examples - is it just a case of adding this file to the project or is there some other compatibility problem that precludes it from working in MVC4 ?

**Comment by andrewdavey** [comment]
Ah, good catch. It needs adding to each of the Postal.Mvc\* projects.

**Comment by plmeister** [comment]
thanks for that - working beautifully now!
