### ISSUE TITLE
CSS Rendering

### ISSUE THREAD

**Issue by harshchandra1984** [andrewdavey/postal#99]
Hello
I would like to check if the library supports css rendering as well. Typically, I don't want to put inline styling with html tags. Something like, 
<html>
<head>
<link rel="stylesheet" type="text/css" href="mystyle.css">
</head>
<body>

<table class="table table-red">
......some table content
</table>

</body>
</html>

Can it be able to parse and put css inline and show proper styling when sent?

Thanks

**Comment by andrewdavey** [comment]
I think this other thread will help: https://github.com/andrewdavey/postal/issues/94
